# Setup
title:        Business Card theme


# About/contact
card:
  name:       John Doe
  titles:     Software Engineer | Student

profiles:
  github:         octocat
  youtube:        user/YouTube
  twitter:        twitter
  instagram:      instagram
  facebook:       facebook
  linkedin:       company/linkedin
  stackoverflow:  1
  twitch:         twitch

# Gems
#gems:
#  - jekyll-paginate

background:
  color:    rgb(43,42,51)

foreground:
  color:    whitesmoke

#Others
markdown: kramdown